FROM php:7.1-apache

RUN apt-get update && \
  apt-get install -y libpq-dev postgresql postgresql-contrib && \
  docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
  docker-php-ext-install pgsql && \
  apt-get purge -y --auto-remove libpq-dev

RUN apt-get update && \
  apt-get install -y msmtp msmtp-mta && \
  apt-get clean

COPY container-conf-files/msmtprc /etc/msmtprc

# Memory Limit
RUN echo "memory_limit=1024M" > $PHP_INI_DIR/conf.d/memory-limit.ini
